repos:
  - repo: https://github.com/charliermarsh/ruff
    rev: 0.11.4  
    hooks:
      - id: ruff
        name: Run ruff (all-in-one linting, formatting, and import sorting)
        language_version: python3.12