name: Python Tests and Code Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pre-commit 

    - name: Install pre-commit hooks
      run: |
        pre-commit install

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files

    - name: Run unit tests with unittest
      run: |
        unittest discover -s tests -p "test_*.py" 