name: Python Tests and Code Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_and_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install project + dev dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run pre-commit checks
      uses: pre-commit/action@v3.0.1

    - name: Run unit tests with pytest
      run: |
        pytest -q
